version: '3.9'

services:
  redis:
    image: redis:6.2-alpine
    container_name: test_redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass 12345

  rabbitmq:
    image: rabbitmq:3-management
    container_name: test_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  reading_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_reading_service
    ports:
      - "8090:8090"
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: "12345"
      REDIS_DB: "0"
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
